.github/workflows/deploy.yml

Import the latest version of the new [Open edX Test Course](https://github.com/openedx/openedx-test-course) into the Nutmeg demo instance every week. See the repository's README for details.

feat: import test course and libraries upon deploy

---

.github/workflows/deploy.yml

This PR initializes codejail before tutor quickstart as mentioned in [this](https://github.com/overhangio/nutmeg-demo/pull/15#issuecomment-1141460335) comment.

fix: initialize codejail before quickstart

---

.github/workflows/deploy.yml

This just adds the forum from its olive PR. Below how I test  this:
1- while on venv of the tutor olive (and while tutor was already running)
2- export VERSION=olive
3- pip install --upgrade --editable git+https://github.com/overhangio/tutor-forum.git@$VERSION#egg=tutor-forum
4- tutor plugins enable forum
5- tutor config save
6- tutor images build forum
7- tutor local init --limit=forum
8- tutor local start forum -d
7- reboot lms/cms and start adding comments on a course
This PR realtes to overhangio/tutor-forum#11 and openedx/cs_comments_service/pull/392

feat: add forum with ruby 3

---

.github/workflows/deploy.yml

The PR enables https://github.com/overhangio/tutor-notes/tree/olive plugin.
Installed and tested locally:
```
git clone -b olive git@github.com:overhangio/tutor-notes.git
pip install -e tutor-notes
tutor plugins enable notes && tutor config save
tutor local launch
```
Then enable Student Notes in Advanced Settings and test in LMS.
---
- probably will rebase after #21

feat: install and enable notes

---

.github/workflows/deploy.yml

This PR adds tutor-contrib-codejail plugin, so loncapa problems work as expected in the sandbox installation. There's already a 15.0.0 codejail image published in our dockerhub repo.
Here is the PR adding support for olive: https://github.com/eduNEXT/tutor-contrib-codejail/pull/28

feat: add codejail with olive support

---

.github/workflows/deploy.yml

PR has changes to enable event routing backends plugin on olive demo.

chore: enable event routing backends plugin on olive demo

---

.github/workflows/deploy.yml
README.md

The PR enables https://github.com/overhangio/tutor-xqueue/tree/olive plugin.
Installed and tested locally:
git clone -b olive git@github.com:overhangio/tutor-xqueue.git
pip install -e tutor-xqueue
tutor plugins enable xqueue && tutor config save
tutor local launch

feat: install and enable tutor xqueue

---

.github/workflows/deploy.yml
README.md

Enabling the forum/discussion plugin, simliar #20.

feat: enable forum plugin

---

.github/workflows/deploy.yml
README.md

Adding forum plugin from PR:
- https://github.com/overhangio/tutor-forum/pull/28

feat: add/enable forum plugin

---

.github/workflows/deploy.yml
README.md

This PR enables notes and xqueue plugins for the Quince demo installation

feat: enable notes and xqueue plugins

---

.github/workflows/deploy.yml

Temporarily disabled the scheduled run, it will be resumed on/after May 9th, 2024, when the redwood branches are cut.

build: temporarily disable the scheduled job

---

.github/workflows/deploy.yml
README.md

The PR enables the following plugins for Redwood sandbox:
- Discovery
- ecommerce
- cairn
- minio
- notes
- xqueue

chore: enable more plugins for redwood sandbox

---

.github/workflows/deploy.yml

Temporarily setting codejail branch to `redwoood`. The branch on upstream is misspelled https://github.com/eduNEXT/tutor-contrib-codejail/pull/53

chore: temporary pin codejail branch name

---

.github/workflows/deploy.yml

Adding changes from https://github.com/edly-io/openedx-nightly-sandbox/pull/8, to ensure SSH connection does not break on MFE builds (and any other build/process that takes a bit of time)

chore: keep SSH alive

---

.github/workflows/deploy.yml
README.md

Update the cron job schedule to run the sandbox reset at 2 AM UTC (7 AM Pakistan time). This will ensure any issues with sandbox build are captured earlier in the day and then sandbox build can be restarted earlier. On average, with max-parallelism=2, sandbox takes around 4-5 hours to complete.

chore: update cron schedule

---

.github/workflows/deploy.yml
README.md

- Add a step in GA to enable PII in aspects
- Enable the following plugins
- credentials
- discovery
- ecommerce
- minio
- xqueue
- notes
- contrib-codejail
- contrib-aspects (v1.2.0)
- Remove edx-event-routing-backend installation as it is now installed within aspects. It is currently only used in contrib-aspects, so it does not need to be installed explicitly.

chore: enable more plugins for Sumac

---

.github/workflows/deploy.yml
README.md

forum has been disabled because v2 branch is causing merge conflicts https://github.com/overhangio/openedx-release-demo/actions/runs/11658968310/job/32458810470. Once fixed/merged upstream, this can be reverted.

temp: disable forum

---

.github/workflows/deploy.yml

Pruning images causes extremely long build times. Let's not do that.

fix: do not "docker prune"

---

.github/workflows/deploy.yml
README.md

This is necessary because we recently faced the following issue on
plugin install:
$ pip install --user --upgrade --src=~/apps/openedx/src --editable git+https://github.com/overhangio/tutor-indigo.git@$sumac#egg=tutor-indi09:34:39 [1510/1510]
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will …

feat: use a virtualenv to run tutor

---

.github/workflows/deploy.yml

Minio was throwing an error on certificates.0003_data__default_modes migration after the upgrade of AWS S3 service.
Until it is fixed, this PR skips minio.

feat: skip minio until it is fixed

---

.github/workflows/deploy.yml
README.md

Adds tutor-contrib-scout-apm (https://github.com/openedx/openedx-tutor-plugins/tree/main/plugins/tutor-contrib-scout-apm) on the sandbox on Axim's request (Dave Ormsbee). The secret has been provided by Dave, which has been added as repo secret.

feat: add Scout APM plugin on Axim request
